name: Deploy to AWS Lambda
run-name: ${{ github.actor }} is deploying the code to AWS Lambda
on:
  push:
    branches:
      - master
env:
  AWS_REGION: ap-southeast-1
  APP_VERSION: 1.0-SNAPSHOT
jobs:
  package_provider:
    name: Setup environment
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - id: set-matrix
        run: |
          echo "matrix=$(cat services.json)" >> $GITHUB_OUTPUT
  deploy_source:
    name: Deploy source code to AWS Lambda
    runs-on: ubuntu-latest
    needs: package_provider
    strategy:
      matrix:
        package: ${{ fromJson(needs.package_provider.outputs.matrix) }}
    steps:
      - name: Print package name
        run: echo ${{ matrix.package }}
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: corretto
          java-version: 17
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Run build with Gradle Wrapper
        run: chmod +x ./gradlew; ./gradlew :${{ matrix.package }}:build
      - name: Upload source code to AWS Lambda
        uses: appleboy/lambda-action@master
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ env.AWS_REGION }}
          function_name: "backend-${{ matrix.package }}"
          zip_file: ${{ matrix.package }}/build/distributions/${{ matrix.package }}-${{ env.APP_VERSION }}.zip